# Generated by Django 3.2.16 on 2022-11-24 17:17

from django.db import migrations, models
import django.db.models.deletion
import shoeting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', shoeting.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.user')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.style')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_right', models.CharField(choices=[('left', '왼발'), ('right', '오른발')], max_length=10)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(choices=[('long', '길어요'), ('normal', '적당해요'), ('short', '짧아요')], max_length=10, null=True)),
                ('width', models.CharField(choices=[('narrow', '좁아요'), ('normal', '적당해요'), ('wide', '넓어요')], max_length=10, null=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.shoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.user')),
            ],
        ),
    ]
