# Generated by Django 3.2.16 on 2022-11-25 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='length',
            field=models.CharField(choices=[('short', '짧아요'), ('normal', '적당해요'), ('long', '길어요')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='width',
            field=models.CharField(choices=[('normal', '적당해요'), ('narrow', '좁아요'), ('wide', '넓어요')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='left_right',
            field=models.CharField(choices=[('right', '오른발'), ('left', '왼발')], max_length=10),
        ),
        migrations.CreateModel(
            name='StyleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.shoe')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeting.style')),
            ],
        ),
    ]
