# Generated by Django 3.2.16 on 2022-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeting', '0002_auto_20221125_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='characteristics',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='length',
            field=models.CharField(choices=[('long', '길어요'), ('normal', '적당해요'), ('short', '짧아요')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='width',
            field=models.CharField(choices=[('wide', '넓어요'), ('normal', '적당해요'), ('narrow', '좁아요')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='left_right',
            field=models.CharField(choices=[('left', '왼발'), ('right', '오른발')], max_length=10),
        ),
    ]
